from models import User, Products
def seed_data():
    productLgoPnkHdie = Products(product_id = 1111, product_short_name = "pinklogohoodie", product_name = "Pink Logo Hoodie", product_status = " In Stock", product_price = "$20.00", product_image = "../assets/products/pinkhoodie.png" , product_keywords = ["HOODIE","PINK","LOGO"], product_desc = "This pink pullover hoodie is 50% cotton and 50% polyester. It has ribbed waistband and cuffs like a split kangaroo pocket. Cozy hood with dyed-to-match adjustable drawcord. Has Jazzhub logo.Imported from France.").put()

    productLgoGrnSwtr = Products(product_id = 3333, product_short_name = "greenlogosweater", product_name = "Green Logo Sweather", product_status = "In Stock", product_price = "$15.00", product_image = "../assets/products/greensweather.png", product_keywords = ["SWEATHER","GREEN","LOGO"],product_desc = "This green sweater is 52% Cotton and 48% Polyester. Features a crew neckline with ribbed collar and ribbed hem and cuffs to lock in warmth. We listen to customer feedback and fine-tune every detail to ensure quality, fit, comfort, satisfaction. Printed Jazzhub logo. Imported from Italy.").put()

    productLgoWhtTsht = Products(product_id = 2222, product_short_name = "whitelogotshirt", product_name = "White Logo T-shirt", product_status = " In Stock", product_price = "$10.00", product_image = "../assets/products/whitetshirt.png" , product_keywords = ["WHITE","T-SHIRT","LOGO"], product_desc = "This white tee is made of 100% cotton. Stock up on must-have basics with this crewneck undershirts featuring a tag-free collar. Everyday made better: we listen to customer feedback and fine-tune every detail to ensure quality, fit, comfort, and satisfaction. Imported from France.").put()

    productLgoAirpods = Products(product_id = 4444, product_short_name = "whitelogoairpods", product_name = "White Logo Airpods", product_status = "Out of Stock", product_price = "$160.00", product_image = "../assets/products/airpods.png", product_keywords = ["WHITE","AIRPODS","LOGO"], product_desc = "Powered by the all-new Apple H1 headphone chip, AirPods deliver a faster and more stable wireless connection to your devices - up to 2x faster when switching between active devices, and a 1.5x faster connection time for phone calls. The H1 chip also drives voice-enabled Siri access and delivers up to 30 percent lower gaming latency. So whether you're playing games, listening to music, or enjoying podcasts, you'll experience higher-quality sound. Comes with Jazzhub logo on case. Includes AirPods, Charging Case, and Lightning to USB Cable. ").put()

    productLgoWhtHdie = Products(product_id = 5555, product_short_name = "whitelogohoodie", product_name = "White Logo Hoodie", product_status = " In Stock", product_price = "$20.00", product_image = "../assets/products/whitehoodie.png" , product_keywords = ["HOODIE","WHITE","LOGO"], product_desc = "This white pullover hoodie is 60% cotton, 40% Polyester. It has Ribbed cuffs and hem, with an embroidered logo. Also has a jersey-lined hood and a kangaroo pocket.  All Jazzhub tops are designed to fit close to the body so it can move with you on and off the stage. Size up for a more chill, relaxed feel. Imported from France.").put()

    productLgoSticker = Products(product_id = 6666, product_short_name = "blacklogosticker", product_name = "Black Logo Sticker 3 pcs", product_status = "In Stock", product_price = "$8.00", product_image = "../assets/products/jazzstickers.png", product_keywords = ["BLACK", "STICKER","LOGO"], product_desc = 'These Jazzhub stickers have COUNTLESS USES! filing, inventory, art, education, etc. Included comes a dispenser box which helps keeps things together and also makes is easy to peel stickers from liner as needed. Permanent adhesive keeps each 8 inches x 2.2inches sticker firmly in place on most surfaces. 3 total count. Has the Jazzhub logo on each sticker.').put()

    productLogoWhtMug = Products(product_id = 7777, product_short_name = "whitelogomug", product_name = "JazzHub Mug", product_status = "In Stock", product_price = "$10.00", product_image = "../assets/products/logomug.png", product_keywords = ["BLACK", "CUP", "MUG", "WHITE","LOGO"]).put()

    productJazzWhtMug = Products(product_id = 8888, product_short_name = "jazzlogomug", product_name = "Jazz It Up Mug", product_status = "In Stock", product_price = "$10.00", product_image = "../assets/products/jazzmug.png", product_keywords = ["BLACK", "CUP", "MUG", "WHITE"]).put()

    productLogoTteBag = Products(product_id = 9999, product_short_name = "totebag", product_name = "JazzHub Tote Bag", product_status = "In Stock", product_price = "$12.00", product_image = "../assets/products/totebag.png", product_keywords = ["BLACK","BAG", "WHITE","LOGO"]).put()

    productLogoJazSup = Products(product_id = 1010, product_short_name = "jazzsupplement", product_name = "Jazzanation Dietary Supplement", product_status = "In Stock", product_price = "$40.00", product_image = "../assets/products/jazzsupp.png", product_keywords = ["BLACK","SUPPLEMENT", "WHITE","LOGO"]).put()

    productLogoBlkSoc = Products(product_id = 1110, product_short_name = "logosock", product_name = "JazzHub Socks", product_status = "In Stock", product_price = "$4.00", product_image = "../assets/products/sock.png", product_keywords = ["BLACK","SOCK","LOGO"],).put()

    productLogoBlkBlt = Products(product_id = 1210, product_short_name = "logobelt", product_name = "JazzHub Belt", product_status = "In Stock", product_price = "$25.00", product_image = "../assets/products/belt.png", product_keywords = ["BLACK","BELT","LOGO", "LEATHER"]).put()
